import { X, FileText, Download, Stethoscope } from "lucide-react";

const PdfModal = ({ isOpen, onClose, filename, onProceed }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-white rounded-[24px] w-full max-w-2xl max-h-[90vh] overflow-y-auto shadow-xl" onClick={(e) => e.stopPropagation()}>
        
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b sticky top-0 bg-white z-10">
          <div className="flex items-center gap-2 font-bold text-sm text-[#2c2c2a]">
            <FileText size={18} className="text-[#72A6BB]" /> AI Medical Report Preview
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg border hover:bg-gray-100 text-gray-500">
            <X size={16} />
          </button>
        </div>

        {/* Body */}
        <div className="p-5 space-y-4">
          <div className="flex items-center justify-between bg-gray-50 p-3 rounded-xl border">
            <div className="flex items-center gap-2 text-xs text-gray-600">
              <FileText size={16} /> <span className="font-semibold">{filename}</span>
            </div>
            <button className="flex items-center gap-1 text-xs px-3 py-1.5 rounded-lg border bg-white hover:bg-gray-100">
              <Download size={14} /> Download
            </button>
          </div>

          <div className="bg-[#f8f7f2] border rounded-xl p-6 space-y-4 text-left">
            <div className="text-center pb-4 border-b-2 border-[#72A6BB]">
              <h2 className="font-bold text-lg text-[#72A6BB]">Medical Diagnosis Report</h2>
              <p className="text-xs text-gray-400 mt-1">Generated by DX AI System — Pending Specialist Review</p>
            </div>
            <div className="grid grid-cols-2 gap-3 text-xs">
              <div className="bg-white p-3 rounded-lg border">
                <span className="text-gray-400 block mb-1">Patient</span>
                <span className="font-bold text-[#2c2c2a]">Patient #227</span>
              </div>
              <div className="bg-white p-3 rounded-lg border">
                <span className="text-gray-400 block mb-1">Date</span>
                <span className="font-bold text-[#2c2c2a]">July 14, 2026</span>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-end gap-2 p-4 border-t bg-gray-50 rounded-b-[24px]">
          <button onClick={onClose} className="px-4 py-2 text-xs rounded-xl border bg-white hover:bg-gray-100">Close</button>
          <button onClick={onProceed} className="flex items-center gap-1 px-4 py-2 text-xs font-semibold rounded-xl bg-[#72A6BB] text-white hover:bg-[#5f92a6]">
            <Stethoscope size={14} /> Proceed to Review
          </button>
        </div>

      </div>
    </div>
  );
};

export default PdfModal;